### ISSUE TITLE
Mistake in documentation?

### ISSUE THREAD

**Issue by damian101** [kimono-koans/dano#9]
In `--help` it says regarding parameter `-j`: "Default is twice the number of logical cores." 
Shouldn't it be half, to match the number of physical cores (on most systems)? Using more threads than can be utilized by the system for threading doesn't sound useful.

**Comment by kimono-koans** [comment]
No, this is as described.

Although you make a good point, this may not be best thing from a theoretical POV -- this is a processor heavy use case, and therefore any switching between tasks might be bad/slower.  

The reason I did it (I think!) is because I saw some speedup where disk IO was the bottleneck in other use cases.

However, AFAICT it doesn't seem to matter in my benchmarks.  Although I'd be very interested in benchmarks where this is not the case.  See below re: a 4 core logical and physical core machine.

Thanks for filing this issue.  You've given me something to chew on.

```
➜  hyperfine -w 3 "dano -t -j=8 *.flac" "dano -t -j=4 *.flac" "dano -t -j=2 *.flac"
Benchmark 1: dano -t -j=8 *.flac
  Time (mean ± σ):      3.050 s ±  0.017 s    [User: 8.787 s, System: 3.194 s]
  Range (min … max):    3.016 s …  3.072 s    10 runs

Benchmark 2: dano -t -j=4 *.flac
  Time (mean ± σ):      3.050 s ±  0.008 s    [User: 8.630 s, System: 3.195 s]
  Range (min … max):    3.036 s …  3.063 s    10 runs

Benchmark 3: dano -t -j=2 *.flac
  Time (mean ± σ):      4.867 s ±  0.005 s    [User: 7.339 s, System: 2.365 s]
  Range (min … max):    4.859 s …  4.876 s    10 runs

Summary
  'dano -t -j=8 *.flac' ran
    1.00 ± 0.01 times faster than 'dano -t -j=4 *.flac'
    1.60 ± 0.01 times faster than 'dano -t -j=2 *.flac'
```
